<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class AbilityCourseQuestionGroupRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "question_jpn" => 'required',
            'ability_course_id' => 'required',
            "question_sound" => 'nullable|file|mimes:audio/mpeg,mpga,mp3,wav,aac',
            "question_img" => 'nullable|file|mimes:jpeg,jpg,png,gif|max:5048',
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
