<?php

namespace App\Http\Requests;

use App\User;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $userEmail = null;
        $id = $this->route('user');
        $getUserById = User::find($id);
        if($getUserById){
            $userEmail = $getUserById->email;
        }

        $ruleValidateEmail = request()->input('email') != '' ? Rule::unique('users')->ignore($userEmail, 'email') : '';
        $rules =  [
            'email' => ['required',$ruleValidateEmail],
            'first_name' => 'required',
            'last_name' => 'required',
            'role' => 'required',
        ];

        return $rules;
    }

    protected function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
